---
name: emmylua-codeformat
description: Fast, powerful, and feature-rich Lua formatting and checking tool.
homepage: https://github.com/CppCXY/EmmyLuaCodeStyle
licenses:
  - MIT
languages:
  - Lua
categories:
  - Formatter

source:
  id: pkg:github/CppCXY/EmmyLuaCodeStyle@1.5.6
  asset:
    - target: darwin_arm64
      file: darwin-arm64.tar.gz
      bin: CodeFormat
    - target: darwin_x64
      file: darwin-x64.tar.gz
      bin: CodeFormat
    - target: linux_arm64_gnu
      file: linux-aarch64.tar.gz
      bin: CodeFormat
    - target: linux_x64_gnu
      file: linux-x64.tar.gz
      bin: CodeFormat
    - target: win_x64
      file: win32-x64.zip
      bin: CodeFormat.exe

bin:
  emmylua-codeformat: "{{source.asset.bin}}"
